<?php

namespace Tests\Unit;

use Tests\TestCase;
use App\Component\RatingComponent;
use App\Users;
class MatchTest extends TestCase
{
    protected $user;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new Users();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testExample()
    {
        $this->assertTrue(true);
    }

    public  function testRating(){
        // Bind data example for test process
        $mMen = $this->user->getData('male');
        $wWomen = $this->user->getData('female');

        $rating = new RatingComponent();
        $testResult = $rating->rating($mMen,$wWomen);
        $resultSample = array(array(2,10,6,8,4),array(4,6,2,8,10),array(8,4,6,2,10),array(2,4,6,8,10),array(2,10,6,8,4));

        $this->assertEquals($testResult,$resultSample);
    }
    public function testMatching(){

        $this->assertTrue();
    }
}
